---
# Playbook zum Neustarten eines Linux-Servers
- name: Reboot Linux Server
  hosts: all
  become: yes
  tasks:
    # Überprüfen, ob ein Neustart erforderlich ist
#    - name: Check if reboot is required
#      command: needrestart -k -p
#      register: reboot_required
#      ignore_errors: yes
#      changed_when: false

    # Server neu starten, wenn erforderlich
    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
#      when: reboot_required.rc == 2

    # Systemlaufzeit nach dem Neustart überprüfen
    - name: Check system uptime after reboot
      command: uptime
      register: uptime_result

    # Laufzeit anzeigen
    - name: Display uptime
      debug:
        var: uptime_result.stdout
