---
- name: Update Linux system and AdGuard Home
  hosts: Adguard
  become: true

  vars:
    adguard_install_dir: /opt/AdGuardHome
    adguard_download_url: https://static.adguard.com/adguardhome/release/AdGuardHome_linux_amd64.tar.gz
    adguard_service_name: AdGuardHome

  tasks:

    - name: Update apt cache and upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Get current AdGuardHome version
      command: "{{ adguard_install_dir }}/AdGuardHome -v"
      register: adguard_current_version
      changed_when: false

    - name: Fetch latest AdGuardHome release info
      uri:
        url: https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest
        return_content: yes
      register: adguard_latest_release

    - name: Set latest version variable
      set_fact:
        adguard_latest_version: "{{ adguard_latest_release.json.tag_name | regex_replace('^v', '') }}"

    - name: Compare versions and decide if update is needed
      set_fact:
        adguard_update_needed: "{{ adguard_current_version.stdout != adguard_latest_version }}"

    - name: Download latest AdGuardHome (if needed)
      get_url:
        url: "{{ adguard_download_url }}"
        dest: /tmp/AdGuardHome_latest.tar.gz
      when: adguard_update_needed

    - name: Extract AdGuardHome archive
      unarchive:
        src: /tmp/AdGuardHome_latest.tar.gz
        dest: /tmp/
        remote_src: yes
      when: adguard_update_needed

    - name: Stop AdGuardHome service
      systemd:
        name: "{{ adguard_service_name }}"
        state: stopped
      when: adguard_update_needed

    - name: Replace AdGuardHome binary
      copy:
        src: /tmp/AdGuardHome/AdGuardHome
        dest: "{{ adguard_install_dir }}/AdGuardHome"
        mode: '0755'
        backup: yes
      when: adguard_update_needed

    - name: Start AdGuardHome service
      systemd:
        name: "{{ adguard_service_name }}"
        state: started
        enabled: yes
      when: adguard_update_needed

    - name: Clean up
      file:
        path: /tmp/AdGuardHome
        state: absent
      when: adguard_update_needed

    - name: Remove downloaded archive
      file:
        path: /tmp/AdGuardHome_latest.tar.gz
        state: absent
      when: adguard_update_needed
