---
- hosts: localhost
  gather_facts: false

  vars:
    sites:
      - ip: 192.168.178.230
        token: 2-qaLp4bIcQxEksHH0HYFIdotgvBl9og0FJREad4iCgfrT5i2maoZ7Stel8AHX8F9E
        validate_certs: false
#      - ip: 192.168.0.2
#        token: 1-uskZv5aFL2siXW9dlVpAINQWeqZNo1xpqDIXXm4yvtM2V8CsjxK9hINydxmye9vH
#        validate_certs: false

  tasks:
    - name: update-truenas-api
      include_tasks: truenas-tasks.yaml
      loop: '{{ sites }}'
