---
- hosts: localhost
  gather_facts: false

  vars:
    siteip: "192.168.178.230"
    token: "5-VW2fLpM7Qavdjt4SrS6PCrDkXo0o329BaFcUdKkW6YK0LdqBg6sW63vcC0MaF00V"

  tasks:
    - name: Check for TrueNAS updates
      uri:
        url: "https://{{ siteip }}/api/v2.0/system/update/check_available"
        method: POST
        headers:
          Authorization: "Bearer {{ token }}"
        validate_certs: no
      register: update_check_response

    - name: Apply TrueNAS updates if available
      uri:
        url: "https://{{ siteip }}/api/v2.0/system/update/apply"
        method: POST
        headers:
          Authorization: "Bearer {{ token }}"
        validate_certs: no
      when: update_check_response.results[item_index].json['available']
      loop_control:
        index_var: item_index
