---
- name: Update System und f체hre Reboot bei Bedarf durch
  hosts: all
  become: yes

  tasks:
    - name: APT Cache aktualisieren
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: System aktualisieren
      apt:
        upgrade: dist

    - name: Alte Pakete entfernen und Cache s채ubern
      apt:
        autoremove: yes
        autoclean: yes
        clean: yes

    - name: Pr체fen, ob ein Reboot erforderlich ist
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot durchf체hren, falls erforderlich
      reboot:
        msg: "Reboot durch Ansible wegen Kernel-/Systemupdate"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Warten bis Host wieder erreichbar ist
      wait_for_connection:
        connect_timeout: 5
        sleep: 5
        delay: 10
        timeout: 300
      when: reboot_required_file.stat.exists
