---
- name: TrueNAS SCALE Backup + Update mit NFS-Upload (via SSH)
  hosts: localhost
  gather_facts: false
  become: true  # nötig für das Mounten der NFS-Freigabe
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"

  vars:
    ansible_user: "root"
    truenas_host: "192.168.178.230"
    truenas_user: "root"  # TrueNAS Benutzer, der SSH-Zugang hat
    truenas_ssh_key: "/root/.ssh/id_rsa_truenas"  # Pfad zu deinem privaten SSH-Schlüssel
    truenas_api_token: "5-VW2fLpM7Qavdjt4SrS6PCrDkXo0o329BaFcUdKkW6YK0LdqBg6sW63vcC0MaF00V"
    backup_filename: "truenas_config_{{ lookup('pipe','date +%F_%H-%M-%S') }}.db"
    nfs_server: "192.168.178.233"
    nfs_share: "/TrueNAS_Backups"
    nfs_mountpoint: "/mnt/nfs_backup"

  tasks:
    - name: Erstelle lokales Backup-Verzeichnis
      file:
        path: "./truenas_backups"
        state: directory
        mode: '0755'

    - name: Erstelle das Backup auf TrueNAS (via SSH)
      ansible.builtin.command:
        cmd: "midclt call system.config.save"
        chdir: "/"
      delegate_to: "{{ truenas_host }}"
      become: true
      become_user: "{{ truenas_user }}"
      environment:
        ANSIBLE_SSH_PRIVATE_KEY_FILE: "{{ truenas_ssh_key }}"

    - name: Warte, bis das Backup abgeschlossen ist (z.B. 30 Sekunden)
      pause:
        seconds: 30

    - name: Hole das Backup von TrueNAS auf den Ansible-Host
      fetch:
        src: "/root/configs/{{ backup_filename }}"
        dest: "./truenas_backups/{{ backup_filename }}"
        flat: yes
      delegate_to: "{{ truenas_host }}"
      become: true
      become_user: "{{ truenas_user }}"

    - name: Erstelle lokalen NFS-Mountpunkt
      file:
        path: "{{ nfs_mountpoint }}"
        state: directory
        mode: '0755'

    - name: Mount NFS-Freigabe
      mount:
        path: "{{ nfs_mountpoint }}"
        src: "{{ nfs_server }}:{{ nfs_share }}"
        fstype: nfs
        opts: defaults
        state: mounted

    - name: Kopiere Backup auf NFS-Freigabe
      copy:
        src: "./truenas_backups/{{ backup_filename }}"
        dest: "{{ nfs_mountpoint }}/{{ backup_filename }}"
        mode: '0600'

    - name: Unmount NFS-Freigabe
      mount:
        path: "{{ nfs_mountpoint }}"
        state: unmounted

    - name: Entferne lokalen NFS-Mountpunkt
      file:
        path: "{{ nfs_mountpoint }}"
        state: absent

    - name: Prüfe auf verfügbare Updates
      uri:
        url: "https://{{ truenas_host }}/api/v2.0/update/check_available"
        method: POST
        headers:
          Authorization: "Bearer {{ truenas_api_token }}"
        body_format: json
        return_content: yes
        validate_certs: no
      register: update_check

    - name: Zeige Update-Status an
      debug:
        msg: "Update-Status: {{ update_check.json.status }}"

    - name: Starte Update falls verfügbar
      when: update_check.json.status == "AVAILABLE"
      uri:
        url: "https://{{ truenas_host }}/api/v2.0/update/update"
        method: POST
        headers:
          Authorization: "Bearer {{ truenas_api_token }}"
        body_format: json
        status_code: 200,202
        validate_certs: no

    - name: Starte TrueNAS neu nach Update
      when: update_check.json.status == "AVAILABLE"
      uri:
        url: "https://{{ truenas_host }}/api/v2.0/system/reboot"
        method: POST
        headers:
          Authorization: "Bearer {{ truenas_api_token }}"
        status_code: 200,202
        validate_certs: no

    - name: Warte bis TrueNAS wieder erreichbar ist
      when: update_check.json.status == "AVAILABLE"
      wait_for:
        host: "{{ truenas_host }}"
        port: 443
        delay: 30
        timeout: 300
