---
- name: Update Homeserver Docker
#  hosts: "{{ my_hosts | d([]) }}"
  hosts: [homeserver]

  tasks:
    - name: Start ei23 du
      ansible.builtin.shell:
        cmd: |
          ei23 du
        executable: /bin/bash
      changed_when: false
      check_mode: false
#      register: disk_usage
