---
- hosts: omv
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

#    - name: Upgrade all packages
#      ansible.builtin.apt:
#        upgrade: dist
#        autoremove: yes
#        autoclean: yes

    - name: Führe omv-upgrade aus (empfohlen für OMV)
      ansible.builtin.command: omv-upgrade
      register: omv_upgrade_result
      changed_when: "'Nothing to do' not in omv_upgrade_result.stdout"
