---
- hosts: localhost
  gather_facts: false

  vars:
    siteip: "192.168.178.230"
    token: "{{ truenas_token }}"

  tasks:
    - name: Check for TrueNAS updates
      uri:
        url: "https://{{ siteip }}/api/v2.0/update/check_available"  # Korrigierter Pfad
        method: POST
        headers:
          Authorization: "Bearer {{ token }}"
        validate_certs: no
      register: update_check

    - name: Debug output
      debug:
        var: update_check

    - name: Apply updates if available
      when: update_check.json.status == "AVAILABLE"
      uri:
        url: "https://{{ siteip }}/api/v2.0/update/update"  # Korrigierter Pfad
        method: POST
        headers:
          Authorization: "Bearer {{ token }}"
        validate_certs: no
